### ISSUE TITLE
Uncaught SyntaxError: The requested module './fortuneService.js' does not provide an export named 'fortuneService'

### ISSUE THREAD

**Issue by mzhKU** [WebEngineering-FHNW/webcl-hs20-2#3]
Ich lasse das Week 2 package laufen, kriege aber den Beschriebenen Error, auch wenn in fortuneService.js der fortuneService exportiert wird..

**Comment by Dierk** [comment]
welchen link genau starten Sie?

**Comment by mzhKU** [comment]
Ich lasse einen lokalen Server laufen (python -m http.server 7900) im "week2" Verzeichnis. Ich rufe wie im Screenshot sichtbar localhost:7900/todo/View.html auf.

Um es wie Sie gezeigt haben mit IntelliJ zu starten, welche Art von Projekt muss man dann anlegen?

![image](https://user-images.githubusercontent.com/1569838/94358033-448f3200-009e-11eb-9ecd-d5226ef3674e.png)

**Comment by Dierk** [comment]
favicon Fehler können sie ignorieren, die haben mit unseren Themen nichts zu tun.

**Comment by mzhKU** [comment]
ja das ist klar, ich muss da das falsche Bild kopiert haben.
